name: Deploy to Cloud Foundry
description: cf push with zero downtime

branding:
  icon: 'truck'
  color: 'blue'

inputs:
  cf_api:
    description: Cloud Foundry API endpoint e.g. https://api.my.cf
    required: true
  cf_org:
    description: Cloud Foundry Organization Name
    required: true
  cf_space:
    description: Cloud Foundry Space Name
    required: true
  cf_username:
    description: Cloud Foundry Username
    required: true
  cf_password:
    description: Cloud Foundry Password
    required: true
  manifest_path:
    description: Cloud Foundry manifest path
    default: manifest.yml
    required: true
  app_path:
    description: Cloud Foundry API endpoint e.g. https://api.my.cf
    default: .
    required: true
  test_domain:
    description: Domain for testing
    default: springernature.app
    required: true

runs:
  using: composite
  steps:
  - name: halfpipe-push
    run: $GITHUB_ACTION_PATH/entrypoint.sh halfpipe-push
    shell: bash
    env:
      INPUT_CF_API: ${{ inputs.cf_api }}
      INPUT_CF_ORG: ${{ inputs.cf_org }}
      INPUT_CF_SPACE: ${{ inputs.cf_space }}
      INPUT_CF_USERNAME: ${{ inputs.cf_username }}
      INPUT_CF_PASSWORD: ${{ inputs.cf_password }}
      INPUT_MANIFEST_PATH: ${{ inputs.manifest_path }}
      INPUT_APP_PATH: ${{ inputs.app_path }}
      INPUT_TEST_DOMAIN: ${{ inputs.test_domain }}
  - name: halfpipe-check
    run: $GITHUB_ACTION_PATH/entrypoint.sh halfpipe-check
    shell: bash
    env:
      INPUT_CF_API: ${{ inputs.cf_api }}
      INPUT_CF_ORG: ${{ inputs.cf_org }}
      INPUT_CF_SPACE: ${{ inputs.cf_space }}
      INPUT_CF_USERNAME: ${{ inputs.cf_username }}
      INPUT_CF_PASSWORD: ${{ inputs.cf_password }}
      INPUT_MANIFEST_PATH: ${{ inputs.manifest_path }}
      INPUT_APP_PATH: ${{ inputs.app_path }}
      INPUT_TEST_DOMAIN: ${{ inputs.test_domain }}
  - name: halfpipe-promote
    run: $GITHUB_ACTION_PATH/entrypoint.sh halfpipe-promote
    shell: bash
    env:
      INPUT_CF_API: ${{ inputs.cf_api }}
      INPUT_CF_ORG: ${{ inputs.cf_org }}
      INPUT_CF_SPACE: ${{ inputs.cf_space }}
      INPUT_CF_USERNAME: ${{ inputs.cf_username }}
      INPUT_CF_PASSWORD: ${{ inputs.cf_password }}
      INPUT_MANIFEST_PATH: ${{ inputs.manifest_path }}
      INPUT_APP_PATH: ${{ inputs.app_path }}
      INPUT_TEST_DOMAIN: ${{ inputs.test_domain }}
  - name: halfpipe-cleanup
    run: $GITHUB_ACTION_PATH/entrypoint.sh halfpipe-cleanup
    shell: bash
    env:
      INPUT_CF_API: ${{ inputs.cf_api }}
      INPUT_CF_ORG: ${{ inputs.cf_org }}
      INPUT_CF_SPACE: ${{ inputs.cf_space }}
      INPUT_CF_USERNAME: ${{ inputs.cf_username }}
      INPUT_CF_PASSWORD: ${{ inputs.cf_password }}
      INPUT_MANIFEST_PATH: ${{ inputs.manifest_path }}
      INPUT_APP_PATH: ${{ inputs.app_path }}
      INPUT_TEST_DOMAIN: ${{ inputs.test_domain }}
